SELECT
    PERCENTILE_CONT(0.25) WITHIN GROUP (ORDER BY EXTRACT(EPOCH FROM (b."EndDate" - b."StartDate")) / 86400.0) AS "P25Days",
    PERCENTILE_CONT(0.5)  WITHIN GROUP (ORDER BY EXTRACT(EPOCH FROM (b."EndDate" - b."StartDate")) / 86400.0) AS "P50Days",
    PERCENTILE_CONT(0.75) WITHIN GROUP (ORDER BY EXTRACT(EPOCH FROM (b."EndDate" - b."StartDate")) / 86400.0) AS "P75Days",
    PERCENTILE_CONT(0.9)  WITHIN GROUP (ORDER BY EXTRACT(EPOCH FROM (b."EndDate" - b."StartDate")) / 86400.0) AS "P90Days"
FROM "Bookings" b;